#!/usr/bin/env bash

subscription_load_reality_server() {
  [[ -r "$XRAY_PROFILE_FILE" ]] || die "No 986 VLESS REALITY server profile is available. Bootstrap Xray first."
  # shellcheck disable=SC1090
  source "$XRAY_PROFILE_FILE"

  local required
  for required in XRAY_PUBLIC_ENDPOINT XRAY_LISTEN_PORT XRAY_SERVER_NAME XRAY_REALITY_PUBLIC_KEY XRAY_REALITY_SHORT_ID; do
    [[ -n "${!required:-}" ]] || die "Xray profile metadata is incomplete: $required"
  done
}

subscription_resolve_identity() {
  local requested_name="${1:-}" row status expires protocols uuid
  subscription_load_reality_server

  SUB_CLIENT_NAME=""
  SUB_CLIENT_UUID=""
  SUB_CLIENT_STATUS=""
  SUB_CLIENT_EXPIRES=""
  SUB_CLIENT_PROTOCOLS=""

  if [[ -n "$requested_name" ]]; then
    validate_username "$requested_name"
    if declare -F seller_exists >/dev/null 2>&1 && seller_exists "$requested_name"; then
      row="$(seller_row "$requested_name")"
      IFS=$'\t' read -r _ status expires protocols uuid _ _ <<< "$row"
      [[ ",$protocols," == *",vless-reality,"* ]] || die "User $requested_name has no VLESS REALITY assignment."
      [[ -n "$uuid" ]] || die "Seller user has no Xray UUID: $requested_name"
      SUB_CLIENT_NAME="$requested_name"
      SUB_CLIENT_UUID="$uuid"
      SUB_CLIENT_STATUS="$status"
      SUB_CLIENT_EXPIRES="$expires"
      SUB_CLIENT_PROTOCOLS="$protocols"
    elif [[ "$requested_name" == "${XRAY_CLIENT_NAME:-}" && -n "${XRAY_CLIENT_UUID:-}" ]]; then
      SUB_CLIENT_NAME="$XRAY_CLIENT_NAME"
      SUB_CLIENT_UUID="$XRAY_CLIENT_UUID"
      SUB_CLIENT_STATUS="bootstrap"
      SUB_CLIENT_EXPIRES="-"
      SUB_CLIENT_PROTOCOLS="vless-reality"
    else
      die "Unknown VLESS REALITY identity: $requested_name"
    fi
  else
    [[ -n "${XRAY_CLIENT_NAME:-}" && -n "${XRAY_CLIENT_UUID:-}" ]] \
      || die "Specify a seller user name."
    SUB_CLIENT_NAME="$XRAY_CLIENT_NAME"
    SUB_CLIENT_UUID="$XRAY_CLIENT_UUID"
    SUB_CLIENT_STATUS="bootstrap"
    SUB_CLIENT_EXPIRES="-"
    SUB_CLIENT_PROTOCOLS="vless-reality"
  fi

  export SUB_CLIENT_NAME SUB_CLIENT_UUID SUB_CLIENT_STATUS SUB_CLIENT_EXPIRES SUB_CLIENT_PROTOCOLS
}

subscription_uri_value() {
  local requested_name="${1:-}" encoded_name
  subscription_resolve_identity "$requested_name"
  encoded_name="$(printf '%s' "986-$SUB_CLIENT_NAME" | jq -sRr @uri)"
  printf 'vless://%s@%s:%s?encryption=none&flow=xtls-rprx-vision&security=reality&sni=%s&fp=chrome&pbk=%s&sid=%s&type=tcp#%s\n' \
    "$SUB_CLIENT_UUID" "$XRAY_PUBLIC_ENDPOINT" "$XRAY_LISTEN_PORT" "$XRAY_SERVER_NAME" \
    "$XRAY_REALITY_PUBLIC_KEY" "$XRAY_REALITY_SHORT_ID" "$encoded_name"
}

subscription_write_uri() {
  local requested_name="${1:-}" output uri
  subscription_resolve_identity "$requested_name"
  output="$CONFIG_DIR/clients/$SUB_CLIENT_NAME-vless-reality.txt"
  uri="$(subscription_uri_value "$SUB_CLIENT_NAME")"
  umask 077
  printf '%s\n' "$uri" > "$output"
  chmod 0600 "$output"
}

subscription_hysteria2() {
  local requested_name="${1:-}"
  require_root
  [[ -n "$requested_name" ]] || die "Usage: 986 subscription hysteria2 NAME"
  validate_username "$requested_name"
  seller_exists "$requested_name" || die "Unknown seller user: $requested_name"
  seller_protocols_has "$requested_name" hysteria2 || die "Seller user has no Hysteria2 assignment: $requested_name"
  hysteria_client_uri_value "$requested_name"
}

subscription_write_mihomo() {
  local requested_name="${1:-}" output node_name hy2_password="" hy2_node=""
  subscription_resolve_identity "$requested_name"
  node_name="986-$SUB_CLIENT_NAME"
  output="$CONFIG_DIR/clients/$SUB_CLIENT_NAME-mihomo.yaml"

  if [[ ",$SUB_CLIENT_PROTOCOLS," == *",hysteria2,"* ]]; then
    hy2_password="$(hysteria_user_password "$SUB_CLIENT_NAME")"
    [[ -n "$hy2_password" ]] || die "Hysteria2 is assigned but credential is missing for $SUB_CLIENT_NAME"
    _hysteria_load_profile
    hy2_node="986-$SUB_CLIENT_NAME-hy2"
  fi

  umask 077
  cat > "$output" <<EOF_YAML
# Generated by 986 VPS Engine $PRODUCT_VERSION
# User: $SUB_CLIENT_NAME
# Status: $SUB_CLIENT_STATUS
# Expires: $SUB_CLIENT_EXPIRES
# Protocols: $SUB_CLIENT_PROTOCOLS
# Local export. Future control-plane milestones will add tokenized HTTPS subscriptions.
mixed-port: 7890
allow-lan: false
mode: rule
log-level: warning

proxies:
  - name: "$node_name"
    type: vless
    server: "$XRAY_PUBLIC_ENDPOINT"
    port: $XRAY_LISTEN_PORT
    uuid: "$SUB_CLIENT_UUID"
    network: tcp
    tls: true
    udp: true
    encryption: none
    flow: xtls-rprx-vision
    servername: "$XRAY_SERVER_NAME"
    client-fingerprint: chrome
    reality-opts:
      public-key: "$XRAY_REALITY_PUBLIC_KEY"
      short-id: "$XRAY_REALITY_SHORT_ID"
EOF_YAML

  if [[ -n "$hy2_password" ]]; then
    cat >> "$output" <<EOF_YAML

  - name: "$hy2_node"
    type: hysteria2
    server: "$HYSTERIA_DOMAIN"
    port: $HYSTERIA_PORT
    password: "$SUB_CLIENT_NAME:$hy2_password"
    sni: "$HYSTERIA_DOMAIN"
    skip-cert-verify: false
    alpn:
      - h3
EOF_YAML
  fi

  cat >> "$output" <<EOF_YAML

proxy-groups:
  - name: "986-PROXY"
    type: select
    proxies:
      - "$node_name"
EOF_YAML
  if [[ -n "$hy2_node" ]]; then
    printf '      - "%s"\n' "$hy2_node" >> "$output"
  fi
  cat >> "$output" <<'EOF_YAML'

rules:
  - MATCH,986-PROXY
EOF_YAML
  chmod 0600 "$output"
}

subscription_write_exports() {
  local requested_name="${1:-}"
  subscription_write_uri "$requested_name"
  subscription_write_mihomo "$requested_name"
}

subscription_uri() {
  local requested_name="${1:-}" output
  require_root
  subscription_write_uri "$requested_name"
  output="$CONFIG_DIR/clients/$SUB_CLIENT_NAME-vless-reality.txt"
  printf 'User   : %s\n' "$SUB_CLIENT_NAME"
  printf 'Status : %s\n' "$SUB_CLIENT_STATUS"
  printf 'Expires: %s\n' "$SUB_CLIENT_EXPIRES"
  printf 'Output : %s\n\n' "$output"
  cat "$output"
}

subscription_mihomo() {
  local requested_name="${1:-}" output
  require_root
  subscription_write_mihomo "$requested_name"
  output="$CONFIG_DIR/clients/$SUB_CLIENT_NAME-mihomo.yaml"
  ok "Mihomo/OpenClash configuration generated for $SUB_CLIENT_NAME"
  printf 'Status   : %s\n' "$SUB_CLIENT_STATUS"
  printf 'Expires  : %s\n' "$SUB_CLIENT_EXPIRES"
  printf 'Protocols: %s\n' "$SUB_CLIENT_PROTOCOLS"
  printf 'Output   : %s\n\n' "$output"
  cat "$output"
}

subscription_status() {
  local requested_name="${1:-}" uri_state='missing' mihomo_state='missing' hy2_state='not assigned'
  subscription_resolve_identity "$requested_name"
  [[ -r "$CONFIG_DIR/clients/$SUB_CLIENT_NAME-vless-reality.txt" ]] && uri_state='ready'
  [[ -r "$CONFIG_DIR/clients/$SUB_CLIENT_NAME-mihomo.yaml" ]] && mihomo_state='ready'
  if [[ ",$SUB_CLIENT_PROTOCOLS," == *",hysteria2,"* ]]; then
    if hysteria_user_exists "$SUB_CLIENT_NAME"; then hy2_state='ready'; else hy2_state='credential missing'; fi
  fi
  printf 'User             : %s\n' "$SUB_CLIENT_NAME"
  printf 'Status           : %s\n' "$SUB_CLIENT_STATUS"
  printf 'Expires          : %s\n' "$SUB_CLIENT_EXPIRES"
  printf 'Protocols        : %s\n' "$SUB_CLIENT_PROTOCOLS"
  printf 'VLESS URI        : %s\n' "$uri_state"
  printf 'Hysteria2        : %s\n' "$hy2_state"
  printf 'Mihomo/OpenClash : %s\n' "$mihomo_state"
  printf 'Remote HTTPS sub : not enabled (control plane/domain pending)\n'
}
