#!/usr/bin/env bash

subscription_load_reality_profile() {
  [[ -r "$XRAY_PROFILE_FILE" ]] || die "No 986 VLESS REALITY profile is available. Bootstrap Xray first."
  # shellcheck disable=SC1090
  source "$XRAY_PROFILE_FILE"

  local required
  for required in XRAY_CLIENT_NAME XRAY_CLIENT_UUID XRAY_PUBLIC_ENDPOINT XRAY_LISTEN_PORT XRAY_SERVER_NAME XRAY_REALITY_PUBLIC_KEY XRAY_REALITY_SHORT_ID; do
    [[ -n "${!required:-}" ]] || die "Xray profile metadata is incomplete: $required"
  done
}

subscription_uri() {
  local requested_name="${1:-}"
  local file
  require_root
  subscription_load_reality_profile

  if [[ -n "$requested_name" ]]; then
    validate_username "$requested_name"
    [[ "$requested_name" == "$XRAY_CLIENT_NAME" ]] || die "Current bootstrap profile belongs to: $XRAY_CLIENT_NAME"
  fi

  file="$CONFIG_DIR/clients/$XRAY_CLIENT_NAME-vless-reality.txt"
  [[ -r "$file" ]] || die "Generated VLESS URI is missing: $file"
  cat "$file"
}

subscription_mihomo() {
  local requested_name="${1:-}"
  local output node_name
  require_root
  subscription_load_reality_profile

  if [[ -n "$requested_name" ]]; then
    validate_username "$requested_name"
    [[ "$requested_name" == "$XRAY_CLIENT_NAME" ]] || die "Current bootstrap profile belongs to: $XRAY_CLIENT_NAME"
  fi

  node_name="986-$XRAY_CLIENT_NAME"
  output="$CONFIG_DIR/clients/$XRAY_CLIENT_NAME-mihomo.yaml"
  umask 077
  cat > "$output" <<EOF_YAML
# Generated by 986 VPS Engine $PRODUCT_VERSION
# Initial local export. Future control-plane milestones will add tokenized HTTPS subscriptions.
mixed-port: 7890
allow-lan: false
mode: rule
log-level: warning

proxies:
  - name: "$node_name"
    type: vless
    server: "$XRAY_PUBLIC_ENDPOINT"
    port: $XRAY_LISTEN_PORT
    uuid: "$XRAY_CLIENT_UUID"
    network: tcp
    tls: true
    udp: true
    encryption: none
    flow: xtls-rprx-vision
    servername: "$XRAY_SERVER_NAME"
    client-fingerprint: chrome
    reality-opts:
      public-key: "$XRAY_REALITY_PUBLIC_KEY"
      short-id: "$XRAY_REALITY_SHORT_ID"

proxy-groups:
  - name: "986-PROXY"
    type: select
    proxies:
      - "$node_name"

rules:
  - MATCH,986-PROXY
EOF_YAML
  chmod 0600 "$output"

  ok "Mihomo/OpenClash configuration generated"
  printf 'Output: %s\n\n' "$output"
  cat "$output"
}

subscription_status() {
  local uri_state='missing' mihomo_state='missing' name='-'
  if [[ -r "$XRAY_PROFILE_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$XRAY_PROFILE_FILE"
    name="${XRAY_CLIENT_NAME:-?}"
    [[ -r "$CONFIG_DIR/clients/${XRAY_CLIENT_NAME:-_}-vless-reality.txt" ]] && uri_state='ready'
    [[ -r "$CONFIG_DIR/clients/${XRAY_CLIENT_NAME:-_}-mihomo.yaml" ]] && mihomo_state='ready'
  fi
  printf 'Bootstrap client : %s\n' "$name"
  printf 'VLESS URI        : %s\n' "$uri_state"
  printf 'Mihomo/OpenClash : %s\n' "$mihomo_state"
  printf 'Remote HTTPS sub : not enabled (control plane/domain pending)\n'
}
